-- +migrate Up 
ALTER TABLE TOURNAMENT_PLAYER_OF_POULE 
    ADD CONSTRAINT UC_TOURNAMENT_POULE_IN_TOURNAMENT_PLAYER_OF_POULE 
    UNIQUE (
        ChessClubName, PlayerID, TournamentName, RoundNumber
    )
;

-- +migrate Down
ALTER TABLE  TOURNAMENT_PLAYER_OF_POULE
    DROP CONSTRAINT UC_TOURNAMENT_POULE_IN_TOURNAMENT_PLAYER_OF_POULE
;