-- +migrate Up
ALTER TABLE CHESSCLUB
    ALTER COLUMN city VARCHAR(100);

-- +migrate Up
ALTER TABLE PLAYER
    ALTER COLUMN city VARCHAR(100);

-- +migrate Up
ALTER TABLE TOURNAMENT
    ALTER COLUMN city VARCHAR(100);
