-- +migrate Up
ALTER TABLE TOURNAMENT_ROUND
	ADD CONSTRAINT CK_ROUND_STARTS_BEFORE_ENDS CHECK (starts < ends);

-- +migrate Down
ALTER TABLE TOURNAMENT_ROUND
	DROP CONSTRAINT CK_ROUND_STARTS_BEFORE_ENDS;