-- +migrate Up
ALTER TABLE CONTACTPERSON
	ADD CONSTRAINT CK_PHONE_NUMBER_TEN_NUMBERS CHECK (LEN(phonenumber) = 10);

-- +migrate Down
ALTER TABLE CONTACTPERSON
	DROP CONSTRAINT CK_PHONE_NUMBER_TEN_NUMBERS;