-- +migrate Up
ALTER TABLE CHESSMATCHMOVE
ADD CONSTRAINT CK_COLOUR_MUST_BE_B_OR_W CHECK (colour = 'B' or colour = 'W');

-- +migrate Down
ALTER TABLE CHESSMATCHMOVE
DROP CONSTRAINT CK_COLOUR_MUST_BE_B_OR_W;