-- +migrate Up
ALTER TABLE TOURNAMENT
ADD CONSTRAINT CHK_REGISTRATION_FEE_GTE_ZERO CHECK (registrationfee >= 0.00)
;

-- +migrate Down
ALTER TABLE TOURNAMENT
DROP CONSTRAINT CHK_REGISTRATION_FEE_GTE_ZERO
;